//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class job
    {
        public int id { get; set; }
        public int posted_by { get; set; }
        public Nullable<int> accepted_by { get; set; }
        public string category { get; set; }
        public string name { get; set; }
        public int salary { get; set; }
        public System.DateTime duration { get; set; }
        public string details { get; set; }
        public int negotiable { get; set; }
        public string preferred_skills { get; set; }
        public int revisions { get; set; }
    }
}
