//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class jobimage
    {
        public int serial { get; set; }
        public int job_id { get; set; }
        public string sample_images { get; set; }
    }
}
