//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobSeekerWeb.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        public int id { get; set; }
        public string user_name { get; set; }
        public string mail { get; set; }
        public string password { get; set; }
        public string name { get; set; }
        public string phone_no { get; set; }
        public string billing_info { get; set; }
        public string picture { get; set; }
        public int ban { get; set; }
    }
}
